# Site settings
title: Anderzenn
name: Anderzenn - Blog
owner: Mads Andersen
email: thedanishmotovlogger@gmail.com
url: "http://anderzenn.github.io"
timezone: Europe/Copenhagen


# Build settings
permalink: /blog/:year/:month/:day/:title
      
# Conversion
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"