name: Anderzenn - Blog
owner: Mads Andersen
email: thedanishmotovlogger@gmail.com
url: "http://anderzenn.github.io"
timezone: Europe/Copenhagen


# Build settings
permalink: /blog/:year/:month/:day/:title
paginate: 7
assets:
  digest: true
      
# Conversion
markdown: kramdown
highlighter: rouge
=======
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
baseurl: http://anderzenn.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
